-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL GENERATED ALWAYS AS IDENTITY,
    email character varying NOT NULL,
    public_key character varying,
    password_hash character varying NOT NULL,
    password_salt character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sessions
(
    id serial NOT NULL GENERATED ALWAYS AS IDENTITY,
    user bigint,
    token bigint,
    expires bigint,
    PRIMARY KEY (id),
    CONSTRAINT user_fk FOREIGN KEY(user) REFERENCES public.users(id),
    CONSTRAINT token_fk FOREIGN KEY(token) REFERENCES public.tokens(id)
);

CREATE TABLE IF NOT EXISTS public.permissions
(
    id serial NOT NULL GENERATED ALWAYS AS IDENTITY,
    token bigint,
    batch bigint,
    permission character varying,
    PRIMARY KEY (id),
    CONSTRAINT batch_fk FOREIGN KEY(batch) REFERENCES public.batches(id),
    CONSTRAINT token_fk FOREIGN KEY(token) REFERENCES public.tokens(id)
);

CREATE TABLE IF NOT EXISTS public.tokens
(
    id serial NOT NULL GENERATED ALWAYS AS IDENTITY,
    expires bigint,
    user bigint,
    signatures character varying,
    token character varying,
    PRIMARY KEY (id),
    CONSTRAINT user_fk FOREIGN KEY(user) REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.leases
(
    id serial NOT NULL GENERATED ALWAYS AS IDENTITY,
    user bigint,
    capacity bigint,
    price bigint,
    start_date bigint,
    end_date bigint,
    signature character varying,
    PRIMARY KEY (id),
    CONSTRAINT user_fk FOREIGN KEY(user) REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.barcodes
(
    id serial NOT NULL GENERATED ALWAYS AS IDENTITY,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.batches
(
    id serial NOT NULL GENERATED ALWAYS AS IDENTITY,
    PRIMARY KEY (id)
);
END;